# Generated by Django 4.2.2 on 2023-06-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_race', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField(verbose_name='publish_time')),
            ],
        ),
        migrations.CreateModel(
            name='RecorderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=32, verbose_name='celery_id')),
                ('state_of_recording', models.CharField(max_length=32, verbose_name='state_of_recording')),
            ],
        ),
        migrations.CreateModel(
            name='RaceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=10, verbose_name='team')),
                ('pilot_name', models.CharField(max_length=200, verbose_name='pilot_name')),
                ('lap_count', models.IntegerField(verbose_name='lap_count')),
                ('lap_time', models.FloatField(verbose_name='lap_time')),
                ('s1_time', models.FloatField(verbose_name='s1_time')),
                ('s2_time', models.FloatField(verbose_name='s2_time')),
                ('team_segment', models.IntegerField(verbose_name='team_segment')),
                ('true_name', models.BooleanField(verbose_name='true_name')),
                ('true_kart', models.BooleanField(verbose_name='true_kart')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.race')),
            ],
        ),
    ]
