# Generated by Django 4.2.2 on 2023-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_delete_recorderprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_recorded',
            field=models.BooleanField(default=False, verbose_name='is_recorded'),
        ),
    ]
