# Generated by Django 4.2.2 on 2023-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_rename_publish_time_race_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='publish_date',
            field=models.DateTimeField(verbose_name='publish_date'),
        ),
    ]
