# Generated by Django 4.2.2 on 2023-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_alter_race_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='celery_recorder_id',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
