# Generated by Django 4.2.2 on 2023-06-26 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_race_celery_recorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date_record_started',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date_record_started'),
        ),
        migrations.AlterField(
            model_name='race',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='publish_date'),
        ),
    ]
