# Generated by Django 4.2.2 on 2023-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0007_race_date_record_started_alter_race_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerecords',
            name='kart',
            field=models.IntegerField(default=0, verbose_name='kart'),
        ),
    ]
