# Generated by Django 4.2.2 on 2023-07-01 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0008_racerecords_kart'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date_record_finished',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date_record_finished'),
        ),
        migrations.AddField(
            model_name='race',
            name='was_recorded_complete',
            field=models.BooleanField(default=False, verbose_name='was_recorded_complete'),
        ),
    ]
