# Generated by Django 4.2.2 on 2023-07-02 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0009_race_date_record_finished_race_was_recorded_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date_record_finished',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_record_finished'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date_record_started',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_record_started'),
        ),
    ]
