# Generated by Django 4.2.2 on 2023-07-10 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0010_alter_race_date_record_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date_record_finished',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_record_finished'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date_record_started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_record_started'),
        ),
        migrations.AlterField(
            model_name='race',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish_date'),
        ),
    ]
