# Generated by Django 4.2.2 on 2023-07-03 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velikiperegoni',
            name='avarage_lap_time',
        ),
        migrations.RemoveField(
            model_name='velikiperegoni',
            name='pilot',
        ),
        migrations.AddField(
            model_name='velikiperegoni',
            name='date_of_race',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 22, 10, 43, 492887), verbose_name='Date of race'),
        ),
        migrations.AddField(
            model_name='velikiperegoni',
            name='race_class',
            field=models.CharField(default=None, max_length=50, verbose_name='Class of the race'),
        ),
        migrations.CreateModel(
            name='PilotsInVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(max_length=100, verbose_name='Pilot')),
                ('avarage_lap_time', models.FloatField(verbose_name='Avarage Lap Time')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.velikiperegoni')),
            ],
        ),
    ]
