# Generated by Django 4.2.2 on 2023-07-03 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_velikiperegoni_avarage_lap_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_race_class', models.CharField(default=None, max_length=50, unique=True, verbose_name='Class of the race')),
            ],
        ),
        migrations.AddField(
            model_name='velikiperegoni',
            name='name_of_the_race',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Race name'),
        ),
        migrations.AlterField(
            model_name='velikiperegoni',
            name='date_of_race',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 22, 25, 38, 918089), verbose_name='Date of race'),
        ),
        migrations.AlterField(
            model_name='velikiperegoni',
            name='race_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.typesofvp', to_field='name_of_the_race_class'),
        ),
    ]
