# Generated by Django 4.2.2 on 2023-07-03 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_pilotsrating_alter_velikiperegoni_date_of_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velikiperegoni',
            name='date_of_race',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 1, 40, 10, 438101), verbose_name='Date of race'),
        ),
    ]
