# Generated by Django 4.2.2 on 2023-07-03 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_velikiperegoni_date_of_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotsinvp',
            name='avarage_lap_time',
        ),
        migrations.AddField(
            model_name='pilotsinvp',
            name='average_lap_time',
            field=models.FloatField(default=0, verbose_name='Average Lap Time'),
        ),
        migrations.AlterField(
            model_name='velikiperegoni',
            name='date_of_race',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 1, 41, 31, 848801), verbose_name='Date of race'),
        ),
    ]
