# Generated by Django 4.2.2 on 2023-07-04 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_remove_pilotsinvp_avarage_lap_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velikiperegoni',
            name='date_of_race',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of race'),
        ),
    ]
