# Generated by Django 4.2.2 on 2023-07-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_alter_velikiperegoni_date_of_race'),
    ]

    operations = [
        migrations.RenameModel('PilotsInVP', 'TempOfPilotsInVP')
    ]