# Generated by Django 4.2.2 on 2023-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_auto_20230704_0315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VelikiPeregoni',
            new_name='BigRace',
        ),
        migrations.RenameModel(
            old_name='TempOfPilotsInVP',
            new_name='TempOfPilotsInBR',
        ),
    ]
