# Generated by Django 4.2.2 on 2023-11-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_rename_velikiperegoni_bigrace_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypesOfVP',
            new_name='TypesOfBR',
        ),
    ]
